# Generated by Django 3.0.3 on 2020-04-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classified',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload an image (max 10MB)', null=True, upload_to='images'),
        ),
    ]
