# Generated by Django 3.0.3 on 2020-04-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20200428_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classified',
            name='pictures',
        ),
        migrations.AddField(
            model_name='classified',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
