# Generated by Django 3.0.3 on 2020-04-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20200428_0414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
